title:             Fullpower Dev
email:             yakri13@gmail.com
description:       Learning Fullstack Web Developer
author: Cameron A. Pickerill-Trinitapoli (Fullmight)
baseurl:           ""
url:               "https://fullmight.github.io/"

colors:
  black: #262626

# Social Profiles
twitter_username:
github_username:   Fullmight
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links

